# Generated by Django 4.1.7 on 2023-04-11 00:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Input',
            fields=[
                ('input_id', models.AutoField(primary_key=True, serialize=False)),
                ('alpha', models.DecimalField(decimal_places=4, max_digits=19)),
                ('betha', models.DecimalField(decimal_places=4, max_digits=19)),
                ('phi', models.DecimalField(decimal_places=4, max_digits=19)),
                ('delta_a', models.DecimalField(decimal_places=4, max_digits=19)),
                ('delta_p', models.DecimalField(decimal_places=4, max_digits=19)),
            ],
        ),
        migrations.CreateModel(
            name='Output',
            fields=[
                ('output_id', models.AutoField(primary_key=True, serialize=False)),
                ('kag', models.DecimalField(decimal_places=4, max_digits=19)),
                ('kagh', models.DecimalField(decimal_places=4, max_digits=19)),
                ('kagv', models.DecimalField(decimal_places=4, max_digits=19)),
                ('kaph', models.DecimalField(decimal_places=4, max_digits=19)),
                ('kach', models.DecimalField(decimal_places=4, max_digits=19)),
                ('teta_a', models.DecimalField(decimal_places=4, max_digits=19)),
                ('k0n', models.DecimalField(decimal_places=4, max_digits=19)),
                ('k0t', models.DecimalField(decimal_places=4, max_digits=19)),
                ('k0h', models.DecimalField(decimal_places=4, max_digits=19)),
                ('k0V', models.DecimalField(decimal_places=4, max_digits=19)),
                ('kpgh', models.DecimalField(decimal_places=4, max_digits=19)),
                ('kpph', models.DecimalField(decimal_places=4, max_digits=19)),
                ('kpch', models.DecimalField(decimal_places=4, max_digits=19)),
                ('teta_p', models.DecimalField(decimal_places=4, max_digits=19)),
                ('foreign_key', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='formula_app.input')),
            ],
        ),
    ]
