# Generated by Django 4.1.7 on 2023-04-05 17:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Input',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alpha', models.DecimalField(decimal_places=10, max_digits=19)),
                ('betha', models.DecimalField(decimal_places=10, max_digits=19)),
                ('phi', models.DecimalField(decimal_places=10, max_digits=19)),
                ('delta_a', models.DecimalField(decimal_places=10, max_digits=19)),
                ('delta_p', models.DecimalField(decimal_places=10, max_digits=19)),
            ],
        ),
        migrations.CreateModel(
            name='Output',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('k0V', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='formula_app.input')),
                ('k0h', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='formula_app.input')),
                ('k0n', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='formula_app.input')),
                ('k0t', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='formula_app.input')),
                ('kag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='formula_app.input')),
                ('kagh', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='formula_app.input')),
                ('kagv', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='formula_app.input')),
                ('kaph', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='formula_app.input')),
                ('kpch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='formula_app.input')),
                ('kpgh', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='formula_app.input')),
                ('kpph', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='formula_app.input')),
                ('teta_a', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='formula_app.input')),
                ('teta_p', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='formula_app.input')),
            ],
        ),
    ]
